### PR TITLE
Add reverse Turing tests

### PR DESCRIPTION
**Pull request by jgru**
Dear Alberto, 

this patch adds several reverse Turing tests to `pafish`. Those newly added checks mimick reverse Turing tests found in real world samples like the UpClicker trojan, leaked source code of Ursnif/Gozi, a "DarkRiver" dropper and XLM 4.0-macros used as droppers.  

Thank you already in advance for considering this PR and kudos for providing `pafish`. 

Best regards
Jan

### CODE REVIEW

**Comment by a0rtega** [comment]
Hey @jgru , thanks for your PR!

It will take me a while to review, merge and create a new release, but I'll get into it as soon as possible!

**Comment by jgru** [comment]
Sure, @a0rtega, please take your time. 
If you have any remarks and/or change requests, please let me know.

**Comment by a0rtega** [comment]
Hey @jgru ,

I merged your PR, outstanding contribution! I made some minor changes to your code, no big deal:

- febe5028d01a79d845811f69c0c5f79efef20f3d: Moved the global variables to the top of the file and added `rtt_` at the beginning of each variable name.
- d78a2e8fb7adc3b1221c520cb439d4b0e214c6e2: Made the window a bit larger for visibility and added a title so users can see that pafish created the window and not any other program.

I'm adding more unrelated changes to the project, but I think I'll publish a new release in the coming days.

Thank you!

**Comment by jgru** [comment]
> Hey @jgru ,
> 
> I merged your PR, outstanding contribution!

Thank you very much, @a0rtega! Glad, that the patch found its way into `pafish`.

> I made some minor changes to your code, no big deal:
> 
> * [febe502](https://github.com/a0rtega/pafish/commit/febe5028d01a79d845811f69c0c5f79efef20f3d): Moved the global variables to the top of the file and added `rtt_` at the beginning of each variable name.
> * [d78a2e8](https://github.com/a0rtega/pafish/commit/d78a2e8fb7adc3b1221c520cb439d4b0e214c6e2): Made the window a bit larger for visibility and added a title so users can see that pafish created the window and not any other program.
> 

Cool, this is actually very helpful! Thanks!

Best regards,
Jan

**Pull request merged**
