### PR TITLE
Fix the compilation under Linux with MinGW cross-compiler v2

### PR DESCRIPTION
**Pull request by serializingme**
Based on previous PR #28. Removed the unnecessary code in the main.c file that handled the disabled VirtualBox MAC check. Related with issue #25.

### CODE REVIEW

**Comment by a0rtega** [comment]
Hi!

As I mentioned in the other ticket #28 , adding the include didn't fix the problem in my setup.

I can add the include anyway if it fixes other setups, but I'll leave the #ifdef block, as a precaution.

Thanks for your pull-reqs!

**Comment by serializingme** [comment]
But did you try to compile without the #ifdef block? I will try to replicate your setup.

**Comment by a0rtega** [comment]
My bad, I tried again without the #ifdef block and it compiled correctly.

I'll merge your changes into dev-chaos branch and then into master, thanks!

**Comment by serializingme** [comment]
@a0rtega no problem eheheh, I actually finished right now from testing in two newly setup Debian an Ubuntu and it worked :D

**Pull request merged**
