### PR TITLE
Curious Fish is Curious

### PR DESCRIPTION
**Pull request by serializingme**
The environments used to perform behavioural analysis of malware need to be stealth, being able to avoid detection by malware is a must because it will spare the researcher or incident responder precious time in the analysis of the incident. Curious Fish (Cufish) aims to help with that, providing information about the execution environment that could be used pre-emptively to improve the sandbox and avoid detection by malware. More information in https://www.serializing.me/2015/06/12/curious-fish-is-curious/

### CODE REVIEW

**Comment by a0rtega** [comment]
Sorry for the delay.

This great to fingerprint obscure systems like sandboxes, but maybe it's too much for a PR to be merged into pafish? If I were you I'd consider creating a new separated project.

**Comment by serializingme** [comment]
You tell me, you're the owner of pafish :D Since I follow the same licensing scheme as pafish I don't see a problem in creating a different project.

**Comment by a0rtega** [comment]
Of course, as long as you follow the GPLv3, it's fine to reuse code :)

**Comment by serializingme** [comment]
Then it's settled, I will create a new project :)

**Pull request closed without merging**
